name: cvms_desktop
description: "A Flutter desktop application for Cloud-based Vehicle Monitoring System using enhanced AES - 128. This desktop app will be used for managing vehicle records, monitor ongoing and outgoing vehicles within JRMSU - Katipunan Campus, manage users (security personnel, CDRRMSU Personnel (admin)) for a thesis project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  #philippine list of provinces and barangays
  philippines_rpcmb: ^0.0.3
  #file selector
  file_selector: ^1.0.3
  #autocomplete
  flutter_typeahead: ^5.2.0
  #qrcode package
  qr_flutter: ^4.1.0
  #Required for initializing and connecting the app to Firebase services
  firebase_core: ^4.0.0
  #Firebase Authentication - used for handling user sign-in, sign-up,
  #and secure access control within the application
  firebase_auth: ^6.0.1
  #Cloud Firestore - NoSQL cloud database for storing and syncing app data in real time
  cloud_firestore: ^6.1.1
  #State management solution using the BLoC (Business Logic Component) pattern
  flutter_bloc: ^9.1.1
  #A package for comparing objects based on their properties, simplifying equality checks in BLoC/Cubit states
  shared_preferences: ^2.5.3
  #A functional programming library for Dart, providing tools for error handling, pattern matching, and functional programming constructsfl
  dartz: ^0.10.1
  #Icons used through-out the app
  phosphor_flutter: ^2.1.0
  #font used in the whole app
  google_fonts: ^7.0.0
  #package for supporting svg files
  flutter_svg: ^2.2.0
  #package for managing windows
  bitsdojo_window: ^0.1.6
  #for advanced data table
  #Icons for iOS-style UI elements
  cupertino_icons: ^1.0.8
  #syncfusion main package
  collection: ^1.19.1
  #charting library
  syncfusion_flutter_charts: ^32.1.24
  syncfusion_flutter_core: ^32.1.24
  syncfusion_flutter_datagrid: ^32.1.24
  calendar_date_picker2: ^2.0.1
  equatable: ^2.0.7
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.1
  #csv
  csv: ^6.0.0
  #filepicker
  file_picker: ^10.3.3
  skeletonizer: ^2.1.2
  # fl_chart: ^0.71.0
  desktop_drop: ^0.7.0
  pdfrx: ^2.2.24
  pdfrx_engine: ^0.3.9

  lottie: ^3.3.2

  #pdf
  pdf: ^3.11.3
  #printing
  printing: ^5.14.2
  screenshot: ^3.0.0
  rxdart: ^0.28.0
  connectivity_plus: ^6.1.5
  internet_connection_checker_plus: ^2.7.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/inter_font_fam/
    - assets/icons/
    - assets/icons/duotone/
    - assets/icons/stencil/
    - assets/icons/windows/
    - assets/icons/3d_fluency/
    - assets/anim/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_font_fam/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter_font_fam/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter_font_fam/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter_font_fam/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter_font_fam/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter_font_fam/Inter-ExtraBold.ttf
          weight: 800
